### ISSUE TITLE
https://mydex.win

### ISSUE THREAD

**Issue by vjoke** [GetScatter/ScatterApps#113]
[Mydex](https://mydex.win) is a true decentralized exchange different from all of the other  DEXs. With decentralized thinking in mind,  mydex has no backend services except the nginx web server,  all of its businesses are implemented with smart contracts. Besides the matching engine, we also implement the risk controlling contract to intercept malicious attacks, and venus contract to release dividends. The asset of users are absolutely secure under multi-layer defending architecture.

**Comment by nsjames** [comment]
PR please according to details in the `README.md`
