### ISSUE TITLE
For dapp list

### ISSUE THREAD

**Issue by davidqw** [GetScatter/ScatterApps#12]
A tokenized advertising service. Click the ADs and get tokens instantly. Each EOS account can claim tokens every 4 hours. The more EPRA you have, the sooner you can claim tokens again.

name: PRABOX
contract: prochaintech
website: http://chain.pro/web-prabox
type: advertisement
desktop/mobile support: both yes

**Comment by nsjames** [comment]
![image](https://user-images.githubusercontent.com/10360675/44784784-6f44ee80-ab97-11e8-8908-20f89b298ca3.png)

**Comment by nsjames** [comment]
This still has not been updated. I'm closing this ticket.
