### ISSUE TITLE
For dapp list

### ISSUE THREAD

**Issue by blockchain-expert** [GetScatter/ScatterApps#15]
Hi James, Our wallet dapp for custom token ( [www.walletforeos.com](http://www.walletforeos.com)  ) supports integration with scatter. Would you please update app list?

**Comment by nsjames** [comment]
This seems to always default to requesting accounts for testnet?

**Comment by blockchain-expert** [comment]
It's updated now. One must select network before integration. Please have a look.

**Comment by nsjames** [comment]
Added
