### ISSUE TITLE
Adding DEXEOS to list

### ISSUE THREAD

**Issue by DiyLecko** [GetScatter/ScatterApps#3]
Hi, i'm a developer of DEXEOS.

DEXEOS, the first decentralized based on EOS use Scatter for SSO.

Can DEXEOS is added to list?

Best Regards.

**Comment by nsjames** [comment]
046ddb53b338d1c5c5f516a21cf6ee6f2f0fbb96

**Comment by nsjames** [comment]
Oh nice! :) Added
