### ISSUE TITLE
Non Simple Mode older version not possible to install

### ISSUE THREAD

**Issue by rastip2** [GetScatter/ScatterApps#404]
I tired to install older version 12.0.0 as recommended on twitter to avoid simple mode, but it does come with first run error
"Scatter Embed Check Failure, Scatter failed to get a list of files available for the latest embedded version"

Is there any older version which works and does not have one account limitations and supports Nano Ledger S?

**Comment by ramijames** [comment]
I recommend: https://github.com/GetScatter/ScatterDesktop/releases/tag/11.0.1
