### ISSUE TITLE
For the dapp list

### ISSUE THREAD

**Issue by berylleigh** [GetScatter/ScatterApps#6]
https://voteos.info/   type:  referendum / wp system.    https://explorer.eosforce.io/#/en/web_wallet_view  type: alternate eos.io blockchain  I haven't tried using desktop with these.  Oh and don't forget: https://medium.com/@liquideos/how-to-build-an-eos-hardware-wallet-a-step-by-step-guide-a62445786c0f

**Comment by nsjames** [comment]
Still no desktop integration, closing this for now.
