### ISSUE TITLE
for the app list

### ISSUE THREAD

**Issue by elorenzoni** [GetScatter/ScatterApps#7]
http://www.goalbarclub.org/simple-game/#/

type : football betting game

**Comment by elorenzoni** [comment]
Hi James
   Thanks for your email. There are some games there. We will be relaunching the application with another interface next week.
   eosflare.io   [Account actions]
  
|  
|   |  
eosflare.io
   |  |

  |

 

  GoalBar Club    [Games]
  
|  
|   |  
GoalBar Club
   |  |

  |

 
goalbarclub (goalbarclub)   [Contract source]

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
goalbarclub (goalbarclub)
 goalbarclub has one repository available. Follow their code on GitHub.  |   |

  |

  |

 

Evandro

**Comment by nsjames** [comment]
Still don't see desktop integration. Closing this for now.
