### ISSUE TITLE
Using exchanges plugin to interact with dapps

### ISSUE THREAD

**Issue by utilsites** [GetScatter/ScatterApps#94]
@nsjames I was thinking about the current hurdles when using blockchain dapps, like staking CPU on EOS and managing private keys, facilitated by scatter. Even so it's complicated for non tech users (the majority).

I'm wondering if a partnership with an exchange (eg. binance), could allow the creation/integration of a plugin with scatter, that would allow an exchange user to interact with dapps using the same javascript interface that scatter uses, but the exchange user just logins with his exchange user account, and the management of private keys and stakes are hidden from him and managed by the Exchange. The plugin would communicate with Exchange server/node to receive blockchain user account info and request the signing of transactions to give to the dapps through the current scatter API.

I think this is possible, can you confirm it?

**Comment by nsjames** [comment]
Possible, but very unfeasible. Exchanges most likely won't want to allow that to happen with their own secure login systems as it puts a potential hole in them. We have something similar coming out soon though. 

This isn't really the place for a discussion about this, want to move it here? https://github.com/GetScatter/SIPs

**Comment by utilsites** [comment]
Moved: https://github.com/GetScatter/SIPs/issues/4
